language: python
cache: pip
python:
  - "3.6"
  - "3.5"
install:
  # Black only runs under Python >= 3.6
  - if [[ $TRAVIS_PYTHON_VERSION != 3.5 ]]; then pip install black; fi
  - pip install -r requirements_dev.txt
script:
  - if [[ $TRAVIS_PYTHON_VERSION != 3.5 ]]; then black --check *.py */; fi
  - isort --check-only --recursive *.py */
  - flake8
  - python -m pytest tests/
