name: Integration
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cove: [ 'oc4ids' , 'ocds' ]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: pip
        cache-dependency-path: '**/requirements*.txt'
    - name: InstallCommon
      run: |
        sudo apt-get install gettext translate-toolkit

    - name: oc4ids
      if: matrix.cove == 'oc4ids'
      run: |
        git clone https://github.com/open-contracting/cove-oc4ids.git
        git clone https://github.com/open-contracting/lib-cove-oc4ids.git

    - name: ocds
      if: matrix.cove == 'ocds'
      run: |
        git clone https://github.com/open-contracting/cove-ocds.git
        git clone https://github.com/open-contracting/lib-cove-ocds.git

    - name: Install
      run: |
        pip install -r requirements_dev.txt
        pip install -r cove-${{ matrix.cove }}/requirements_dev.txt
        # Make sure we're using local libs rather than one brought in
        # via requirements.
        pip install -e ./lib-cove-${{ matrix.cove }}/
        pip install -e .
        pip list

    - name: Compile Messages
      if: matrix.cove == 'ocds'
      run: |
        cd cove-${{ matrix.cove }}
        python manage.py compilemessages
        # Ensure that compilemessages gets run for lib-cove-web
        pushd /opt/hostedtoolcache; pwd; django-admin compilemessages; popd

    - name: Test cove instance
      run: |
        cd cove-${{ matrix.cove }}
        DJANGO_SETTINGS_MODULE=cove_project.settings py.test

    - name: Test cove lib instance
      run: |
        cd lib-cove-${{ matrix.cove }}
        py.test
