name: Integration
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cove: [ 'oc4ids' , 'ocds' , 'bods']
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: InstallCommon
      run: |
        sudo apt-get install gettext translate-toolkit

    - name: oc4ids
      if: matrix.cove == 'oc4ids'
      run: |
        git clone https://github.com/open-contracting/cove-oc4ids.git
        git clone https://github.com/open-contracting/lib-cove-oc4ids.git

    - name: ocds
      if: matrix.cove == 'ocds'
      run: |
        git clone https://github.com/open-contracting/cove-ocds.git
        git clone https://github.com/open-contracting/lib-cove-ocds.git

    - name: bods
      if: matrix.cove == 'bods'
      run: |
        git clone https://github.com/openownership/cove-bods.git
        cd cove-bods
        git checkout update-requirements-jsonschema
        cd ..
        git clone https://github.com/openownership/lib-cove-bods.git

    - name: Install
      run: |
        pip install -r cove-${{ matrix.cove }}/requirements.txt
        pip install -r cove-${{ matrix.cove }}/requirements_dev.txt
        pip install -r requirements_dev.txt
        # Make sure we're using local libs rather than one brought in
        # via requirements.
        pip install -e .
        pip install -e ./lib-cove-${{ matrix.cove }}/
        pip list

    - name: Compile Messages
      if: matrix.cove == 'ocds'
      run: |
        cd cove-${{ matrix.cove }}
        python manage.py compilemessages
        # Ensure that compilemessages gets run for lib-cove-web
        pushd /opt/hostedtoolcache; pwd; django-admin compilemessages; popd

    - name: Test cove instance
      run: |
        cd cove-${{ matrix.cove }}
        DJANGO_SETTINGS_MODULE=cove_project.settings py.test

    - name: lib-cove-ocds requirements
      if: matrix.cove == 'ocds'
      run: |
        # Upgrade Django for lib-cove-ocds tests, as they rely on some details
        # of entity quoting that have changed
        pip install --upgrade Django

    - name: Test cove lib instance
      run: |
        cd lib-cove-${{ matrix.cove }}
        py.test
